# Generated by Django 4.0.6 on 2022-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kar',
            name='token',
            field=models.CharField(default='a', max_length=64),
        ),
        migrations.AlterField(
            model_name='karmand',
            name='token',
            field=models.CharField(default='a', max_length=64),
        ),
    ]
