# Generated by Django 4.0.6 on 2022-08-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_employerr_delete_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employerr',
        ),
    ]
