# Generated by Django 4.0.6 on 2022-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_remove_kar_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='kar',
            name='is_done',
            field=models.IntegerField(default=0),
        ),
    ]
